### ISSUE TITLE
problem with solution for "Perform a linear regression for each fold and calculate the training and test error"

### ISSUE THREAD

**Issue by lilisbeit** [learn-co-curriculum/dsc-cross-validation-lab#3]
The solution is showing that the mean squared error for each fold is the same, which doesn't seem right.  I think this is because the code never re-defined X_train and y_train in the for loop, so X_train and y_train are still pulling the definition from several cells above.

**Comment by hoffm386** [comment]
Hi Lili, thank you for flagging! You are correct, the old version of this solution was repeatedly using the same `X_train` and `y_train` instead of creating new ones for each fold. The updated solution (as part of a larger rewrite) now uses different data for each fold, and also compares the results to the scikit-learn results for an extra check. You can view that change here: https://github.com/learn-co-curriculum/dsc-cross-validation-lab/commit/a680a334c416e825a187339a8f83c52d1e9d6349
